spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanjia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


  thymeleaf:
    cache: false # 关闭thymeleaf缓存

mybatis:
  type-aliases-package: com.hanjia.entity
  mapper-locations: classpath:mapper/*.xml
